#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("THRVI.Resource", IsApplication=true)]

namespace THRVI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_down = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int locations_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonCreateStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int edit_text_style = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_discard = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_new = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_search = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ProgressBarStyle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int spinner_style = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08001f
			public const int add = 2131230751;
			
			// aapt resource value: 0x7f080005
			public const int btnCreateTrailer = 2131230725;
			
			// aapt resource value: 0x7f08000c
			public const int btnUpdateTrailer = 2131230732;
			
			// aapt resource value: 0x7f08000f
			public const int buttonMoveTrailers = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int buttonOptions = 2131230736;
			
			// aapt resource value: 0x7f08000e
			public const int buttonViewTrailers = 2131230734;
			
			// aapt resource value: 0x7f08000b
			public const int checkboxUpdateWhiteX = 2131230731;
			
			// aapt resource value: 0x7f080004
			public const int checkboxWhiteX = 2131230724;
			
			// aapt resource value: 0x7f080020
			public const int discard = 2131230752;
			
			// aapt resource value: 0x7f08001c
			public const int etSearch = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int linearLayout1ProgressBar = 2131230749;
			
			// aapt resource value: 0x7f08001b
			public const int listView = 2131230747;
			
			// aapt resource value: 0x7f080015
			public const int llContainer = 2131230741;
			
			// aapt resource value: 0x7f080006
			public const int progressBar = 2131230726;
			
			// aapt resource value: 0x7f08000d
			public const int progressBarUpdate = 2131230733;
			
			// aapt resource value: 0x7f08001e
			public const int search = 2131230750;
			
			// aapt resource value: 0x7f080003
			public const int spinnerLocation = 2131230723;
			
			// aapt resource value: 0x7f08000a
			public const int spinnerUpdateLocation = 2131230730;
			
			// aapt resource value: 0x7f080011
			public const int textView1 = 2131230737;
			
			// aapt resource value: 0x7f080019
			public const int txtHeaderLocation = 2131230745;
			
			// aapt resource value: 0x7f080017
			public const int txtHeaderMake = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int txtHeaderModel = 2131230744;
			
			// aapt resource value: 0x7f080016
			public const int txtHeaderStockNumber = 2131230742;
			
			// aapt resource value: 0x7f08001a
			public const int txtHeaderWhiteX = 2131230746;
			
			// aapt resource value: 0x7f080012
			public const int txtLocation = 2131230738;
			
			// aapt resource value: 0x7f080001
			public const int txtMake = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int txtModel = 2131230722;
			
			// aapt resource value: 0x7f080013
			public const int txtMove = 2131230739;
			
			// aapt resource value: 0x7f080000
			public const int txtStockNumber = 2131230720;
			
			// aapt resource value: 0x7f080008
			public const int txtUpdateMake = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int txtUpdateModel = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int txtUpdateStockNumber = 2131230727;
			
			// aapt resource value: 0x7f080014
			public const int txtWhiteX = 2131230740;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_create_trailer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_update_trailer = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int move_trailers = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int options = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int row_trailer = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int view_trailers = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int actionbar = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int deletebar = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int location_prompt = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int mainMenuMoveTrailers = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int mainMenuOptions = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int mainMenuViewTrailers = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
